networks:
  network:
    external: true

volumes:
  db_data:
  cache_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:3000'
    environment:
      - NODE_ENV=production
    container_name: auth-app
    env_file: '.env.production'
    networks:
      - network

  auth-db:
    image: postgres:latest
    container_name: auth-db
    env_file: '.env.production'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - network

  auth-cache:
    image: bitnami/redis:latest
    container_name: auth-cache
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - cache_data:/data
    env_file: '.env.production'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASE=${REDIS_DATABASE}
    restart: unless-stopped
