# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up environment variables
        run: |
          echo "POSTGRES_USER=db_user" > .env
          echo "POSTGRES_PASSWORD=db_password" >> .env
          echo "POSTGRES_DB=db" >> .env
          echo "POSTGRES_PORT=5432" >> .env
          echo "REDIS_URL=127.0.0.1" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env
          echo "REDIS_PASSWORD=cache_password" >> .env
          echo "REDIS_DATABASE=0" >> .env
          echo "JWT_SECRET=jwt-secret" >> .env

      - name: Make setup.sh and teardown.sh executable
        run: chmod +x ./test/setup.sh && chmod +x ./test/teardown.sh

      - name: Install Packages
        run: bun install

      - name: Setup tests containers
        run: bash ./test/setup.sh

      - name: Run tests
        run: bun test

      - name: Teardown tests containers
        run: bash ./test/teardown.sh

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        # with:
        #   node-version: 20
        #   registry-url: https://npm.pkg.github.com/
      # - run: npm ci
      - run: bun install
      - run: bun run publish:build
        env:
          NPM_CONFIG_TOKEN: ${{secrets.NPM_CONFIG_TOKEN }}
